# Generated by Django 4.2.7 on 2023-11-20 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_new_id_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='collection',
            new_name='product',
        ),
    ]
