# Generated by Django 4.2.7 on 2023-11-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_collection_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='product',
            field=models.ManyToManyField(related_name='collections', to='store.product'),
        ),
    ]
