# Generated by Django 4.2.7 on 2024-11-21 13:18

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_productmedia_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='store/images'),
        ),
    ]
