version: "3"
services:
  db:
    container_name: youcef-api-POSTGRES
    image: postgres
    restart: always
    volumes:
      - ./data/db-api:/var/lib/postgresql/data-api
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "5400:${POSTGRES_PORT}"
    networks:
      - youcef-api-network
    labels:
      io.portainer.accesscontrol.teams: Backend
    pgadmin:
      container_name: youcef-api-pgadmin4
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      ports:
        - "1234:80"
      networks:
        - youcef-api-network
      labels:
        io.portainer.accesscontrol.teams: Backend
  networks:
    default:
      driver: bridge
    youcef-api-network:
      external: true
  volumes:
    postgres: {} 
